image: goblinogm/goblin-buildchain

cache:
  paths:
  - vendor

test:
  services:
    - name: goblinogm/gremlin-server-python:latest
      alias: gremlin-server
  image: goblinogm/goblin-buildchain
  script:
  - pip install -U -r requirements.txt
  - python setup.py test

pages:
  script:
  - pip install -U -r requirements.txt
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master
